title: Willard Nixon
email: 
description: >-
  Full Stack Developer & Creative Problem Solver
baseurl: ""
url: "https://willard-nt.github.io"

# Social media usernames
github_username: willard-nt
linkedin_username: yourusername

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
